SELECT * FROM STUDENTS;

CREATE SEQUENCE STUDENTS_STUDID_SEQ
    START WITH 1
    INCREMENT BY 1;


CREATE OR REPLACE TRIGGER TRI_STUDENTS_STUDID_SEQ
BEFORE INSERT ON STUDENTS
FOR EACH ROW 
BEGIN 
    IF Inserting AND :NEW.STUD_ID IS NULL THEN 
        SELECT STUDENTS_STUDID_SEQ.NEXTVAL INTO :NEW.STUD_ID FROM DUAL;
    END IF;
END; 
